### ISSUE TITLE
Peer count

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1020]
On Schlesi, Peer are probably dropping us because of responsiveness issue.

![image](https://user-images.githubusercontent.com/22738317/81925457-dcedb400-95e0-11ea-8dce-7343475c326a.png)

Currently we use a single thread to handle Network IO and processing
including cryptography which can block for over 1ms, block processsing, state_transition, hashTreeRoot which are significantly slower (100ms).

**Comment by q9f** [comment]
related to #989 ?

**Comment by arnetheduck** [comment]
@mratsim do you have any supporting evidence that the peer count is low specifically because of the processing delay?

In general, #989 is stalled for 2 reasons - the deposit issue that was fixed, and another issue in the sync manager where it sometimes is unable to continue syncing when there's a slot gap in the wrong place - restarting it helps at that point.

**Comment by arnetheduck** [comment]
we are generally peering fine on altona - low peer counts are related to sync issues often, where peers get descored.
