### ISSUE TITLE
0.11.3 regression: "Attestation may arrive in any order" (?)

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#1056]
The regression might just be an issue in the test suite but here is a screenshot that showcase the changes:

![image](https://user-images.githubusercontent.com/22738317/82562559-c2ce4b80-9b75-11ea-89ae-d97a8f6f4fd6.png)

On the bottom right, this is the current devel, the changes trigger a "new" warning since now the comparison is changed to striclty `<` instead of `<=`:

Devel
https://github.com/status-im/nim-beacon-chain/blob/e2885d34456f2f1e943a380c788c290385eb1763/beacon_chain/state_transition.nim#L146-L167

Master
https://github.com/status-im/nim-beacon-chain/blob/9636ca3e17628d4bfbdc2a29006e5385fc398e66/beacon_chain/state_transition.nim#L81-L87

The test in question is:
https://github.com/status-im/nim-beacon-chain/blob/e2885d34456f2f1e943a380c788c290385eb1763/tests/test_attestation_pool.nim#L51-L78

In particular the line 73 which uses `discard` instead of check.

**Comment by tersec** [comment]
This isn't really a regression per se in the 0.11.3 test suite, since `devel` runs the test suite fine.

That being said, sure, it's fine to `discard process_slots()` where necessary in `tests/`.

**Comment by arnetheduck** [comment]
well, yes and no - I think the tests need fixing if they're calling `process_slots` in an invalid way (except to stress test it)

**Comment by tersec** [comment]
If we want to preserve as much as possible from the previous behavior, it I believe suffices to pass the EF spec tests to only return false on the `==` case, not the unequal case of the inequality, but that seems worse. There are only two other places in the test suite which I had to keep as `discard` rather than either `doAssert` or `check:`, out of a couple dozen or so total calls to `process_slots()`, so it seemed reasonable enough.

But, sure, it'd be worthwhile at some point to examine the remaining (3 total it should be, once this fork choice branch get merged, now) `discard process_slots(...)` cases to check whether they make sense. My instinct is that if they're asserting in that scenario, they shouldn't be called at all, since it means the slot's already what they specify.
