### ISSUE TITLE
BeaconClock refactoring.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-beacon-chain#1111]
Our current BeaconClock using procedures from Nim's stdlib times.nim. One of this procedures is `getTime()` https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L889-L909 . This procedure do not uses MONOTONIC clock to get time and so can produce weird behavior. I suspect it happens here https://github.com/status-im/nim-beacon-chain/issues/1098

**Comment by arnetheduck** [comment]
the beacon clock has to use a non-monotonic (wall) clock - it's what the spec says, because slot time is tied to "world" time. 

the client should gracefully handle jumps in time (and leap seconds etc) - either by shutting down with an explanation to the user or by taking appropriate action - there are proposals to include time diagnostics in the protocol to help deal with some of these issues - but until then, eth2 clients cannot work properly if they don't run a computer with the correct time set.

**Comment by cheatfate** [comment]
@arnetheduck how you can explain this one epoch lag (384 seconds) in issue #1098 ?

**Comment by cheatfate** [comment]
Also the only way to detect jumps in time is too have both clocks running and keep association of `wall_clock: monotonic_clock`.

**Comment by arnetheduck** [comment]
what we're looking for basically is situations where we've processed `slot N` and are now asked to process `slot X < N` - we don't need a monotonic clock for that. 

I don't know what caused #1098 - it could be a time jump (which should also be seen in log timestamps) or an off-by-one somewhere in the code - for example the epoch rounding code for getLocalWallSlot is fishy - if NTP resets the clock by a second or two, the slot might jump a whole epoch.

**Comment by cheatfate** [comment]
This is compressed quote from @deme logs.
```
DBG 2020-05-26 22:58:46+02:00 local_head_slot=0 queue_last_slot=928 ... wall_head_slot=928 workers_count=0
...
DBG 2020-05-26 23:00:43+02:00 local_head_slot=0 queue_last_slot=928 ... wall_head_slot=928 workers_count=1
...
DBG 2020-05-26 23:01:43+02:00 local_head_slot=0 queue_last_slot=928 ... wall_head_slot=896 workers_count=0
```
As you can see there no time jumps but for some reason procedure `getLocalWallSlot` which uses only procedures from `spec` folder produced such weird last slot.

**Comment by cheatfate** [comment]
This topic do not have enough support, so i'm closing it.
