### ISSUE TITLE
Finalization failing

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#1212]
For at least some weeks, up to a couple of months, finalization on `make eth2_network_simulation` and
> N=0; while ./scripts/launch_local_testnet.sh --testnet 0 --nodes 4 --log-level TRACE --disable-htop -- --verify-finalization --stop-at-epoch=8; do N=$((N+1)); echo "That was run #${N}"; sleep 71; done

worked fine. I could run them basically indefinitely without a single finalization failure.

For me, this was true until https://github.com/status-im/nim-beacon-chain/commit/c773e10c1a085a2c60915ee4f8c05ec4489bbbbc, while the next commit, https://github.com/status-im/nim-beacon-chain/commit/cf6a869e9e18a3f3748528841b68ddf046e77cfe#diff-5648ab1ca8795603b38ee26eaf9feab5R61-R65 broke it such that it's still broken today.

Proposed fixes have been:

1. don't give any keys to the bootstrap node in the simulation;
2. wait to load all the keys before writing out the network address file; and
3. lower the reconnect timers.

If I understand (1) correctly, it'd mainly address the 0 peers vs 1 peer case, which isn't what I'm mostly seeing. Instead, it hovers between 1 to 2 peers, mostly, sometimes getting three peers.

Some re-ordering already landed in `devel`: https://github.com/status-im/nim-beacon-chain/pull/1185 which helps a bit.

I reduced `make eth2_network_simulation` validators from 256 to 128.

(3) is okay for testing, and helps somewhat locally, but isn't an actual solution:
```
diff --git a/beacon_chain/eth2_network.nim b/beacon_chain/eth2_network.nim
index 27f175e..b3af8cf 100644
--- a/beacon_chain/eth2_network.nim
+++ b/beacon_chain/eth2_network.nim
@@ -203,13 +203,13 @@ const
   ConcurrentConnections* = 10
     ## Maximum number of active concurrent connection requests.
 
-  SeenTableTimeTimeout* = 10.minutes
+  SeenTableTimeTimeout* = 10.seconds
     ## Seen period of time for timeout connections
-  SeenTableTimeDeadPeer* = 10.minutes
+  SeenTableTimeDeadPeer* = 10.seconds
     ## Period of time for dead peers.
   SeenTableTimeIrrelevantNetwork* = 24.hours
     ## Period of time for `IrrelevantNetwork` error reason.
-  SeenTableTimeClientShutDown* = 10.minutes
+  SeenTableTimeClientShutDown* = 10.seconds
     ## Period of time for `ClientShutDown` error reason.
   SeemTableTimeFaultOrError* = 10.minutes
     ## Period of time for `FaultOnError` error reason.
```

This isn't a reasonable thing to spam actual testnets with.

**Comment by tersec** [comment]
An current example: the CI finalization checks had gotten decently, albeit not perfectly, reliable, but because of this, https://github.com/status-im/nim-beacon-chain/pull/1211 might pass finalization, maybe not. Who knows? Detailed discussion is for that PR, not this issue, but there's nothing obviously broken about it, it's quite simple, and yet I'd be quite hesitant to merge even such things without the justified confidence that working local finalization provides.

**Comment by zah** [comment]
The most significant difference introduced in the "failing" commit is that it moves the point in time where the local validator keys are loaded. Prior to the change, the loading of the keys was very intertwined with the initialization of the networking code which worked like this:

1) We start listening for incoming connections (we write out the node address file)
2) We start loading the keys, allowing some incoming packets to be processed in between each loaded key.
3) After all keys are loaded, we try connect to other nodes.

This delicate logic existed because step 1 is important in the simulation because the bootstrap node needs to complete it before the rest of the nodes can be started (they wait for the address file in order to know the bootstrap node's ENR address). If we just load all the keys before any network activity, this would trivially fix the problems, but it will result in a significantly slower simulation start-up time (we can perhaps add this as an option and use it only the CI).

-----------

After the change, the key loading has been made fully independent of the network initialization code and it was assumed that the `await asyncSleep(0)` that is executed after each loaded key is enough to keep the networking code performing decently, but apparently that's not the case.

A proper long-term fix here is to introduce a more general capability of processing CPU intensive work (such as key loading) in background threads. 

Short-term, more CLI options for tweaking the the start-up logic and various time-out parameters or the way that keys are assigned between nodes hopefully should mitigate the problem.

**Comment by tersec** [comment]
> The most significant difference introduced in the "failing" commit is that it moves the point in time where the local validator keys are loaded. Prior to the change, the loading of the keys was very intertwined with the initialization of the networking code which worked like this:
> 
>     1. We start listening for incoming connections (we write out the node address file)
> 
>     2. We start loading the keys, allowing some incoming packets to be processed in between each loaded key.
> 
>     3. After all keys are loaded, we try connect to other nodes.
> 
> 
> This delicate logic existed because step 1 is important in the simulation because the bootstrap node needs to complete it before the rest of the nodes can be started (they wait for the address file in order to know the bootstrap node's ENR address). If we just load all the keys before any network activity, this would trivially fix the problems, but it will result in a significantly slower simulation start-up time (we can perhaps add this as an option and use it only the CI).
> 
> After the change, the key loading has been made fully independent of the network initialization code and it was assumed that the `await asyncSleep(0)` that is executed after each loaded key is enough to keep the networking code performing decently, but apparently that's not the case.
> 
> A proper long-term fix here is to introduce a more general capability of processing CPU intensive work (such as key loading) in background threads.
> 
> Short-term, more CLI options for tweaking the the start-up logic and various time-out parameters or the way that keys are assigned between nodes hopefully should mitigate the problem.

Well, right now it's too unreliable to trust locally, and it looks like the CI might have similar issues. So I prefer slower startup but more trustworthy over faster but routinely fails.

**Comment by zah** [comment]
Do you see any obstacles to trying some of the suggested fixes yourself? Since on my system the yielding in between the key loading is apparently enough of a remedy, I cannot really confirm that the problem is fixed by a local change. If you are willing to wait, I can of course push the proposed fixes one by one, but we are likely to arrive at the solution more slowly this way

**Comment by tersec** [comment]
I listed the suggested fixes tried already and what was done regarding them -- I think the initial batch was mostly covered, and they did help. I'll try your further suggestion of:
> If we just load all the keys before any network activity, this would trivially fix the problems, but it will result in a significantly slower simulation start-up time (we can perhaps add this as an option and use it only the CI).

Except that I don't see why limit to the CI? That's one use case, but it's a local issue for me at least well, and it sounded from the Discord discussion like other people had experienced similar issues (thus the variety of individual workarounds that it emerged that people had).

**Comment by zah** [comment]
Please note that when you slow down the simulation start-up time, you must also pair this with a roughly matching increase in the `--genesis-offset=` parameter in `start.sh`. Otherwise, the nodes might be late for their first validation duties.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/1217 should help here.

**Comment by tersec** [comment]
This seems to be improved enough in the last couple weeks it's worth closing.
