### ISSUE TITLE
Weak Build Versioning and Dependency Management

### ISSUE THREAD

**Issue by eschorn1** [status-im/nim-beacon-chain#1314]
Enhancement, difficulty:high, severity:low.

**Description**: The Nim language provides the `nimble` tool to support the build configuration and version management of dependencies. However, the `beacon_chain.nimble` file does not specify any dependency versions beyond `nim` itself. Instead, the project utilizes GitHub submodule functionality to specify versions.

The `.gitmodules` file specifies a number of dependencies to include as excerpted below. However, specific versions are not articulated as commonly found in similar [Go](https://blog.golang.org/using-go-modules) and [Rust](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) toolchains; rather, the `master` is specified.

~~~
[submodule "vendor/nim-libp2p"]
	path = vendor/nim-libp2p
	url = https://github.com/status-im/nim-libp2p.git
	ignore = dirty
	branch = master
~~~

While a local .git repository does contain commit information such as in `nim-beacon-chain/.git/modules/vendor/nim-blscurve/HEAD`, this is not straightforward to change or configure for specific build targets. As a result, it can be difficult to determine and/or specify dependency versions.

Challenges with dependency management and versioning introduces risk from outdated dependencies which is one of the most common, serious and exploited application vulnerabilities. An attacker will attempt to identify and utilize publicly known vulnerabilities in outdated dependencies to exploit the application. There appears to be no simple mechanism to determine the freshness of dependencies.

**Impact**: Untracked dependency version management can lead to non-reproducible builds, incompatible deployments and increased debug difficulty. Further,  executables may incorporate known vulnerabilities from outdated dependencies that were subsequently remediated. 

**Recommendation**: Implement a mechanism that more overtly integrates explicit dependency versioning and management into the build flow. This would include the ability to easily define a specific build configuration and the configuration placed under version control itself (as appropriate). The mechanism should be able to inspect a configuration and report outdated dependencies.

**Comment by stefantalpalaru** [comment]
> While a local .git repository does contain commit information such as in nim-beacon-chain/.git/modules/vendor/nim-blscurve/HEAD, this is not straightforward to change or configure for specific build targets. As a result, it can be difficult to determine and/or specify dependency versions.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by zah** [comment]
The issue brings valid concerns about the fact that we don't have an easy-to-use or perhaps even automated mechanism that tells us when some of our third-party dependencies have become out of date (specialized tools can even alert you regarding known vulnerabilities). In practice, this is a real problem - I remember occasions where we've upgraded a library after a significant delay (e.g. Milagro, News, etc).

As the OP also correctly acknowledges, this is a difficult problem to solve due to the lack of mature solutions for both Nim and C/C++. To improve the ecosystem for us and everybody else, we are sponsoring the development of [lockfiles](https://myers.io/2019/01/13/what-is-the-purpose-of-a-lock-file-for-package-managers/) in Nimble which is an important pre-requisite for implementing the suggested improvements. For reference, this work is underway here:

https://github.com/bobeff/nimble/commits/feature/lock-file

**Comment by stefantalpalaru** [comment]
> we don't have an easy-to-use or perhaps even automated mechanism that tells us when some of our third-party dependencies have become out of date

`make update-remote`, documented here: https://github.com/status-im/nim-beacon-chain/wiki/Developer-tips-&-tricks or here: https://github.com/status-im/nimbus-build-system#update-remote

> In practice, this is a real problem

In practice, you can't automate dependency upgrades because upstream breaks backwards compatibility way too often.

> I remember occasions where we've upgraded a library after a significant delay (e.g. Milagro, News, etc).

That's because the porting work was not justified by those new features or bug fixes provided in new versions.

> To improve the ecosystem for us and everybody else, we are sponsoring the development of lockfiles in Nimble

Those lockfiles are not an improvement. Language-specific package managers are not an improvement. Getting to know your tools instead of chasing fads - now that's the real improvement!
