### ISSUE TITLE
Implement peer cycling

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#2341]
When the mesh is missing subnet peers, disconnect worst scored peers and find better ones.

**Comment by sinkingsugar** [comment]
This is already happening, it's already in stable, gossip will disconnect worst scored peers indeed.
Finding better peers is another thing tho.
There is no strategy implied in the gossipsub spec, the application should provide better scores and better peers. So the implementation should indeed be NBC side. But it's a more complex issue.

**Comment by zah** [comment]
This was one of the suggested milestones discussed in our February planning meeting. If it was not added by you, it was probably something @arnetheduck had in mind.

**Comment by arnetheduck** [comment]
This is an NBC-level task indeed.

When Nimbus connects to a set of peers, they may or may not cover the relevant gossip topics - when coverage is low, one should go out and connect to more peers that are part of the relevant stability attestation subnet per ENR information. 

Because what "relevant topics" are changes over time, this is a process that should be ongoing for the lifetime of the application.

Further, because we have a limit on number of open connections, sometimes we have to disconnect peers - this should be done according to several metrics:

* is the peer currently useful from a subnet perspective?
  * if the peer is not currently useful, is the peer connected to subnets that few other peers are connected to?
* are we currently low on outgoing peers and is the peer an incoming peer? 
* has the peer been connected for a long time?
  * is the peer responding to enr / metadata update requests? these need to happen periodically to follow peers across subnets
* does the peer have a high gossip score?
* has the peer answered any block requests usefully?

As such, gossipsub should generally only disconnect abusive peers but not merely "useless" ones - this requires higher-level information than gossip can provide.

**Comment by sinkingsugar** [comment]
@arnetheduck thanks for clarifying and sketching it out for me.
Can you clarify the `ENR information` point? is it something we have there already from discovery? how come it's not used already?

**Comment by arnetheduck** [comment]
What we're really after is the [stability subnet](https://github.com/ethereum/eth2.0-specs/blob/v1.0.0/specs/phase0/p2p-interface.md#attestation-subnet-bitfield):

* supplied in ENR through discovery
* supplied in metadata request for connected peers

When preparing to send attestations, "useful peers" from above are those whose subnet map matches the subnets we're about to be sending on - both the subnets we're interested in and the subnets _they_ are subscribed to changes over time, the former every epoch, the latter more rarely

**Comment by arnetheduck** [comment]
we're not using it yet, because we simply connect to lots of peers and manage the subnets through subscriptions - this ticket is about improving that process such that when we're no longer connected to any useful peers, we do something active about it.

**Comment by kdeme** [comment]
To get started, I had in mind to do something like this:

Two peer thresholds, the lower mark (soft cap) and higher mark (hard cap).

At interval:
- Check peer count: if not >= lower mark -> launch a regular discovery query + dial discovered peers.
    - Perhaps better would be to have this event based eventually.
    - Might have to tune this to search already earlier for peers with specific stability subnets.
- Else:
    - Check all connected peers and filter out the ones that are useful for us (This currently would mean the ones on subnets useful to us at this point in time).
    - Take left over peers and sort them by score, disconnect the x lowest ones. x = upper threshold - lower threshold
    - If not all useful subnets are covered, launch a discovery query specific for those subnet and & dial the discovered peers (until all subnets or max threshold reached).

So in short, use the lower mark to dial peers "generally", and the higher mark to dial drop the least useful and dial peer specific to stability subnets required.

At interval (Could be included at interval above, but this can probably be ran at a slower rate):
- ping connected peers to get stability subnet information
- verify this stability subnet information with potential gossip mesh information of that peer (to be certain that peers are not providing invalid metadata about their stability subnets)
    - This could also be verified at the above interval.

At new subnet subscriptions:
- Check amount of peers on that subnet(s)
- Clear out peers (score + not useful), see above.
- When subnets not covered: launch a discovery query specific for those subnet and & dial the discovered peers

Additionally:
- Have incoming vs outgoing limitations. For example: Hard cap of 30% on incoming connections, outgoing can take up 100%
- Instead of looking for peers that are useful for us (meaning: that are on the subnets we care about at that moment), we could also target peers to maximize all subnets, even when we only need few at a time. That way there is no need to launch new searches at new subnet subscriptions. At the cost of more peers probably.
- An emergency query could also be done before sending attestation and still not having the right amount of peers on the subnet (will this help at all?)
- Perhaps we could also not have an upper threshold, and just limit us on the incoming connections. Not sure about this though.

Discovery potential improvements:
- When we don't have enough peers on the right subnet, we need to launch a discovery query for these. Discovery could have an ENR cache holding (previously unused) query results of the last x minutes. This might provide us peers faster, but uncertain if it is needed and if it would work that well...

In general these steps will probably need some tuning and perhaps require additional metrics to keep track of it.
My intuition also says that it is probably better/more convenient to just cover all subnets, this could be a first step.
