### ISSUE TITLE
Algorithm designed for sharding

### ISSUE THREAD

**Issue by rsshevkar** [status-im/nim-beacon-chain#2378]
Hello Inventors,
I am a research student and interested in the sharding algorithm used for Ethereum 2.0.

**Comment by mratsim** [comment]
Hello @rsshevkar and welcome to the Eth2 community.

Sharding has evolved a lot since its first community description 3 years ago.
The latest iteration is described here: https://hackmd.io/@HWeNw8hNRimMm2m2GH56Cw/sharding_proposal

Research and algorithms discussions around sharding happen in the ethresear.ch forum: https://ethresear.ch/c/sharding

For history about the first sharding proposal, you can start with this thread: https://ethresear.ch/t/sharding-phase-1-spec-retired/1407
A collection of **outdated** resources here: https://eth.wiki/en/sharding/sharding-introduction-r-d-compendium

You will also likely find the annoted Eth2 specs interesting to understanding the rationale behind the design of phase 0 (currently deployed)
- [Ben Edgington's annotated spec](https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/) 
- [Vitalik's annotated spec](https://github.com/ethereum/annotated-spec/blob/master/phase0/beacon-chain.md)
- [Danny Ryan's annotated spec](https://notes.ethereum.org/@djrtwo/Bkn3zpwxB)

Just to be clear, **any sharding proposal that doesn't mention DAS (Data Availability Sampling) is outdated as of March 2021**. This may evolve in the future.

There is a video by Dankrad and Vitalik explaining the design of committee-based sharding as well:
- https://hackmd.io/@hww/workshop_feb_2021
- https://vitalik.ca/files/misc_files/eth2_sharding.pdf
- https://www.youtube.com/watch?v=uGeIDNEwHjs&t=3948s
