### ISSUE TITLE
Lazy pruning

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#2381]
Currently, we prune the database when updating the head, as part of the finalization process:

https://github.com/status-im/nimbus-eth2/blob/769225b5913a294afff2d98e29653cc0102fe5c2/beacon_chain/consensus_object_pools/blockchain_dag.nim#L915

The pruning should instead be moved to a separate function that's invoked at slot-end:

https://github.com/status-im/nimbus-eth2/blob/769225b5913a294afff2d98e29653cc0102fe5c2/beacon_chain/nimbus_beacon_node.nim#L892

In general, the pruning needs to be balanced with other processing - as such, on each slot we should limit the pruning to no more than 1 epoch.

As such, we also need to start keeping track of the prune point, and potentially all known heads - this would mean:

* when a head is added, write a new to-prune head list to the database
* for each prune round, read the prune marker and prune head list (being careful to not prune still-relevant states and blocks), prune data from that epoch then update prune marker as well as the heads list to remove already-pruned heads

**Comment by mratsim** [comment]
Moving pruning to slot end was implemented in #2384 and #2422

- Pruning the DAG is kept immediately after finalization so that attestations targeting invalid or already finalized chains are dropped right away.
- Pruning the state is done at slot end and now shows up as a very large bottleneck. Trying to prune only part of it will not be enough.
- Pruning the epoch refs is done at slot end as well, they can be cleaned up in one go.

On a high-end NVMe SSD
![image](https://user-images.githubusercontent.com/22738317/111885217-b8aff000-89c6-11eb-8274-539bc2251dd6.png)
