### ISSUE TITLE
Error: unhandled exception: Asynchronous task [runSlotLoop() at nimbus_beacon_node.nim:985] finished with an exception "KeyError"

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#2471]
Steps to reproduce:

1) Run a beacon node with an arbitrary number of validators for an extended period of time
2) Stop the node and delete the `secrets` and `validators` folders.
3) Add new validators to the node and restart it
4) Observe a crash after several epochs:

```
/data/beacon-node-builds/stable-large/repo/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(360) NimMain
/data/beacon-node-builds/stable-large/repo/beacon_chain/nimbus_beacon_node.nim(1918) main
/data/beacon-node-builds/stable-large/repo/beacon_chain/nimbus_beacon_node.nim(1641) doRunBeaconNode
/data/beacon-node-builds/stable-large/repo/beacon_chain/nimbus_beacon_node.nim(1275) start
/data/beacon-node-builds/stable-large/repo/vendor/nim-chronicles/chronicles.nim(329) run
/data/beacon-node-builds/stable-large/repo/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(489) reraiseException
/data/beacon-node-builds/stable-large/repo/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(407) reportUnhandledError
/data/beacon-node-builds/stable-large/repo/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(358) reportUnhandledErrorAux
Error: unhandled exception: Asynchronous task [runSlotLoop() at nimbus_beacon_node.nim:985] finished with an exception "KeyError"! [FutureDefect]
```

The issue was reported by an end user using v1.0.10 and it's currently observed on a fleet server where we are using the `v1+v2` slashing protection mode.

**Comment by mratsim** [comment]
Unfortunately the log (is libbacktrace activated?) aren't very helpful so let's proceed by elimination.

1. `KeyError` is a ValueError. It should be caught by diligent use of `{.raises: [Defect].}` which is done in the slashing protection files:

https://github.com/status-im/nimbus-eth2/blob/v1.1.0/beacon_chain/validators/slashing_protection_v1.nim#L8

https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/validators/slashing_protection_v2.nim#L8

2. v1+v2 is only if checks on top that wouldn't trigger KeyError

https://github.com/status-im/nimbus-eth2/blob/v1.1.0/beacon_chain/validators/slashing_protection.nim#L173-L233
https://github.com/status-im/nimbus-eth2/blob/v1.1.0/beacon_chain/validators/slashing_protection.nim#L269-L290

3. KeyError can only occur in tables or json field access. The slashing DBs doesn't use either. In particular:

- The KV store and SQLite3 KV-store use KvResult /Result everywhere https://github.com/status-im/nim-eth/blob/0f3bb61/eth/db/kvstore_sqlite3.nim
- Slashing protection does use `ValidatorPubKey` which when deserialized can refer to a Table https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/spec/crypto.nim#L49-L55, https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/slashing_protection_v1.nim#L571
  However, Slashing protection never needs to deserialize that keys as it does no signing or verification.
  The loadWithCache is also forced to only raise Defect and cannot raise KeyError: https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/spec/crypto.nim#L24, https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/spec/crypto.nim#L91-L109. It should also have proper handling of missing keys since they are tested first.

**Comment by mratsim** [comment]
Now regarding the deletion/restart:

The `validators` dir is defined here 

https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/conf.nim#L633-L637.

It includes the slashing protection
![image](https://user-images.githubusercontent.com/22738317/114425007-f0bae500-9bb8-11eb-8e72-6297a6862da6.png)

The validator pool is initialized here
https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/nimbus_beacon_node.nim#L329
It does NOT read the slashing DB to setup validators:
https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/validator_pool.nim#L22-L29

The validators are added to the beacon node here: 

https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/nimbus_beacon_node.nim#L384-L393
https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/validator_duties.nim#L58-L96

with the validatorKeys iterator being

https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/keystore_management.nim#L279-L306

and using the `validatorsDir` function mentioned the very first time.

Hence the `attachedValidators` table should also not throw a KeyError, since all validators are loaded at the node start within the data structure. https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/beacon_node_types.nim#L157-L159

It is interesting to note that the validator pool doesn't enforce `Defect` but does use getOrDefault throughout
https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/validator_pool.nim#L55-L57.
The special `nil` (instead of Option or propagating an exception) is used to denote a non-attached validator https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/validator_duties.nim#L98-L130

**Comment by arnetheduck** [comment]
since it's a `KeyError`, any func that is annotated with `raises: [Defect]` will not raise it - however, this does not apply to `async` functions: they can raise anything even when in "theory" annotated - ergo, `KeyError` comes from an `async` proc

**Comment by mratsim** [comment]
Indeed, but some modules are not yet tagged with `raises: [Defect]` like the validator_pool.

**Comment by arnetheduck** [comment]
I believe I tagged them all (in nimbus-eth2 that is) in a recent cleanup, ie https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/validators/validator_pool.nim#L8

**Comment by arnetheduck** [comment]
the one thing that didn't work was indeed the place where we use concepts - ie that still needs cleanup / getting rid of : https://github.com/status-im/nimbus-eth2/blob/61669f269d8ddacc65ea7b87455a797856abbf9a/beacon_chain/validators/slashing_protection.nim#L8

**Comment by arnetheduck** [comment]
No `KeyError`:s observed for a decent amount of time and `raises` coverage significantly increased - we can close this one for now
