### ISSUE TITLE
Allow comma separator for REST API query arrays

### ISSUE THREAD

**Issue by mcdee** [status-im/nim-beacon-chain#2518]
ETH 2 standard API endpoints such as https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateValidators have an array query parameter.  There is no standard for passing arrays in URLs, however there are two common methods to do this:

1. pass the parameter multiple times, e.g. `id=foo&id=bar`
2. pass a comma-separated list of the parameters e.g. `id=foo,bar`

Existing API implementations allow for the latter option.  They may or may not allow the former option, however it is not used as commonly with clients because it takes up more space in the URL and total URL length is limited.

At current, nimbus supports 1) but not 2).  Would it be possible for nimbus to support 2) as well, to enable wider compatibility?

**Comment by cheatfate** [comment]
If you use method `1` everything could be easily formalized, because of format (for example `id=` means empty value and `id=&` still represents empty value).
But as soon as you start using method `2`, you are not able to use `,` commas in your value because it could be treated as an array.
So i have some questions about `2` option.
1. How to treat `id=,` and `id=,&`. Is this construction produces `[None, None]`, or `[None]` or `,` value (`None` here is an empty value).
2. How to treat percent-encoded comma value `%2C` (url-encoded value of comma).
3. How to tread strings like `id=1,2&id=3` is it supposed to be decoded as `[1,2,3]` or as `[3]` only.

Is there present any specification around? Because there much more ways of representing arrays in url-encoded string.

P.S. @mcdee Sorry for the delay, just missed this issue

**Comment by mcdee** [comment]
My personal opinions on the items from having worked with similar APIs in the past are:

1) This would be `[None,None]`
2) The URL would be unescaped prior to processing, so e.g. `id=foo%2Cbar` would be the two-element array `[foo,bar]`
3) This individual query values would be concatenated as they are at current so this would be `[1,2,3]`

Because there is no standard for arrays different implementations have slightly different views as to what to do to parse the input.  However, the above would give sane enough rules to work with.

It should also be noted that although the array format has options the element format is clear _i.e._ either a simple number or a hex string.  As such, all of the 'None' items can just be ignored (or errored if you prefer a more strict interpretation; the API says return a 400 if a validator ID is invalid, but up to you if `None` means "nothing here" or "a validator with index/key of None").

**Comment by cheatfate** [comment]
@mcdee if `id=foo%2Cbar` translates into `[foo, bar]` it means that its impossible to pass `,` as value. So all array values could not hold `,` as value.

I understand that ETH2 REST values do not imply to use `,`, but it could become a big waste of time to write specific REST server only to be able to proceed ETH2 REST arrays. So there should be present some kind of specification, because right now it looks like some non-formalized magic.

**Comment by mcdee** [comment]
Arrays in query parameters were never standardized by W3C or IETF, and I doubt that it is a road that would be any fun to go down but you're welcome to try.

In the meantime, given the lack of standard then if you want to not decode `%2C` prior to array parsing that's also fine.  I think that having an implementation that matches others in the case of regular and valid input is a significant step forwards, regardless of how irregular or invalid input is handled.

**Comment by cheatfate** [comment]
@mcdee could you please expand "others" to client names at least so i can check implementation of this clients.

**Comment by mcdee** [comment]
Lighthouse and teku.

**Comment by cheatfate** [comment]
This issue has been fixed in `unstable`.
Now nimbus REST server supports both methods.
