### ISSUE TITLE
Key import issues with custom key directory

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#2686]
Also reproduced by @emizzle.

Experienced on Pyrmont and Prater, the same command with custom validator directory

`build/nimbus_beacon_node deposits import \
--data-dir=build/data/shared_prater_0 "<YOUR VALIDATOR KEYS DIRECTORY>"`

may work in some cases and fail to import keys in other cases.

**Comment by emizzle** [comment]
In my case, the issue was that the deposit file had been renamed to ` .json` (that is a space followed by ".json") inadvertantly. With the file name like this, *regardless of whether or not the files were in a custom directory*, I received the following warning after running the import command:
```
WRN 2021-06-29 18:18:42.500+10:00 Invalid keystore                           tid=1232522 file=keystore_management.nim:548 err="/home/dappnode/Documents/ETH2-mainnet/validator_keys/ .json(1, 0) Unexpected token 'tkBracketLe' in place of 'object start bracket'"
```
To be clear, this happened when not running the import command from a custom directory:
```
build/nimbus_beacon_node deposits import --data-dir=build/data/shared_mainnet_0
```
As well running the import command from a custom directory:
```
build/nimbus_beacon_node deposits import --data-dir=build/data/shared_mainnet_0 "/home/dappnode/Documents/ETH2-mainnet/validator_keys/"
```

**Comment by mratsim** [comment]
So it might be a confusing error message then.

**Comment by cheatfate** [comment]
@emizzle is it keystore created by `nimbus` or by other client?

**Comment by emizzle** [comment]
> @emizzle is it keystore created by `nimbus` or by other client?

It was provided to me as part of the node program by @arnetheduck -- he should have that info.

**Comment by zah** [comment]
Well, there was not really a bug here. The deposit file is not a keystore file, so it's reasonable that it produces an "Invalid Keystore" warning.
