### ISSUE TITLE
Insufficient private key validation (covers nim-blscurve)

### ISSUE THREAD

**Issue by veorq** [status-im/nim-beacon-chain#2693]
It seems that the derivation of a pubkey in nimbus-eth2 from a private only checks that the private scalar is not zero, whereas as per the IETF specs it should be in "1 <= SK < r".  You can for example get a pubkey that is the point at infinity it the scalar is a multiple of the group order r.

See:

https://github.com/status-im/nimbus-eth2/blob/44f652f704f14c67e648f2b14dee652d44b858c5/beacon_chain/spec/crypto.nim#L88-L93

where nim-blscurve's `publicFromSecret()` is doing the zero check, and calls blst's scalar multiplication, which does not perform additional checks:

https://github.com/status-im/nim-blscurve/blob/fd4956f5d65129e9b475e654903a84303395eb92/blscurve/blst/blst_min_pubkey_sig_core.nim#L122-L132

I'd recommend to check 1 <= SK < r instead of just SK != 0 in nim-blscurve's `publicFromSecret()`, and report the error as invalid secret key in nimbus-eth2's `toPubKey()`.

**Comment by mratsim** [comment]
I've added a full description of the situation in https://github.com/status-im/nim-blscurve/pull/115.

In short,

1. with BLST backend, all public APIs that instantiate a `SecretKey` type enforced `0 < SK < r`. This means that the input of `publicFromSecret` is respecting the spec preconditions (unless process memory is tampered with or corrupted).
2. with MIRACL backend, which hasn't been used in production since https://github.com/status-im/nimbus-eth2/pull/2152 (so removed ~9 days after mainnet launch), it was indeed possible to deserialize a SK >= r.

In the future,
PR https://github.com/status-im/nimbus-eth2/pull/2700 fixes the MIRACL backend and merges an additional precondition range check in `publicFromSecret` as defensive programming. It should never fail if using the public APIs for constructing `SecretKey`.
