### ISSUE TITLE
Use `ValidatorIndex` or similar type for such fields in SSZ types

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#2769]
Currently, the SSZ types are defined such that validator index fields have the `uint64` type, unlike the purpose-specific `Slot`, `Epoch`, etc types for other also-64-bit-unsigned-integers. This isn't ideal in terms of catching potential bugs.

https://github.com/status-im/nimbus-eth2/pull/2429 thus-far unsuccessfully attempts to address one example of this.

**Comment by arnetheduck** [comment]
> Currently, the SSZ types are defined such that validator index fields have the uint64 type, unlike the purpose-specific Slot, Epoch, etc types for other also-64-bit-unsigned-integers. This isn't ideal in terms of catching potential bugs.

One persistent issue in the codebase is that although we use specific and distinct types, they are being converted without further thought to their respective validity ranges - to add these to the serialized types would require the serializers to gain the ability to perform extended validation which probably is tricky (ie "is the committee index valid in this slot?")

**Comment by arnetheduck** [comment]
This has been resolved by distinguishing between "serialization types" and "code types" - ie `ValidatorIndex` is a code type that carries additional restrictions on top of what goes in serialization - fundamentally, the problem here is that types are being overloaded for multiple purposes which doesn't end well when the types need to be used in diverse contexts: ie deserializing streams that conform to the _serialization_ constraints is useful even if they don't conform to some other, higher-level constraints (for example being in some particular range determined at runtime, like validatorindex ends up being)

The notion that a type can be used both for serialization _and_ high-level code is not generally valid - it's more of a shortcut that works sometimes.
