### ISSUE TITLE
Allow forced outgoing connections while soft-limiting total number of connections

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#3031]
https://github.com/status-im/nimbus-eth2/pull/2888 introduces more aggressive peer kicking in order to get to a healthier mesh more quickly and work around a priority issue in the current semaphore handling of libp2p (being worked on as discussed in https://github.com/status-im/nim-libp2p/issues/595 and https://github.com/status-im/nim-libp2p/pull/629).

The strategy to kick peers is helping, but has a few issues that need tackling:

* sometimes, it's not right to kick peers at all - each peer might be a useful participant in the mesh and kicking any of them degrades connectivity
* kicking peers, pausing (because async loop) then making outgoing connections is vulnerable to incoming connection stuffing where a long accept queue might prevent making outgoing connections for prolonged periods of time, even where the current, fairly aggressive kicking strategy, works under "normal" conditions.

The systemic solution is to allow outgoing connections above a "soft incoming cap"  (but still below a hard total connection cap), for example by introducing a `forced` dialling mechanism discussed elsewhere.

**Comment by Menduist** [comment]
My thoughts:
- I think we all agree that we still need a hard `--max-conn` for various reasons
- It means that if we want a force dial, we will _have_ to kick peers when we reach max-peers, even if we have a lower soft-cap
- So if we have to kick peers eventually, let's just do that? + a better control over incoming, see below

So, if we improve the current dial kicker, by implementing it directly in libp2p (pseudocode to get my point across):
```nim
proc forceDial(peerId: peer) =
  let connection = await internalConnect(peerId)
  if connection.failed: return
  let semaphoreSlot = semaphore.acquire()
  while not semaphoreSlot.finished: await kickOnePeer()
  return connection
```
That alleviates problem n2, since we are certain that we'll be able to dial a peer, no matter what. This also allow us to kick peers only when we know that we have a viable peer on the other side.
Also, since we get a slot in the semaphore queue before kicking, it's impossible to frontrun us


> sometimes, it's not right to kick peers at all

I would like to add a metric to track that, but for instance, on a server with `--subscribe-all-subnets=true --max-peers=100`, over the course of an hour, 131 peers were kicked, for a total score of.. 0. Meaning, they were not subscribed to _any_ topic

> soft incoming cap

libp2p clearly lacks the ability to give control over incoming connections to applications, and that's something we definitively want to improve. My question would be, what kind of control do you want for nimbus? Just set a cap on incoming? Have a dynamic cap?

**Comment by arnetheduck** [comment]
> I think we all agree that we still need a hard --max-conn for various reasons

this is something that can be controlled on the nimbus side - in particular, it can be high enough that it acts as a safety net (think .. 500) - we simply stop connecting at that point, and because incoming connections will have hit a lower limit, we'll be coasting until something else happens.

>  we will have to kick peers when we reach max-peers

"maybe" - or we just put the setting higher - that said, we might want to kick peers independently of any maximum peers setting.

> My question would be, what kind of control do you want for nimbus? Just set a cap on incoming? 

this doesn't really matter that much, but by and large, once we have a healthy number of peers (say .. 100), we stop accepting incoming connections - this would be a "--target-peers" setting or something like this, and both incoming and outgoing peers should count.

The point here is that up to a certain limit, we want peers to connect to us as much as possible, but after that, we enter a zone where only connections that are likely to yield results are deemed useful. In this zone, we can consider an independent kicker that just kicks junk peers to bring things back to the target count, but we should never ever kick potentially useful peers here, nor should we block outgoings.

>   let semaphoreSlot = semaphore.acquire()
>  while not semaphoreSlot.finished: await kickOnePeer()

this works ... but I don't really see the point? I mean, it's like actively trying to come up with a convoluted workaround with a loop and a wait (the wait itself is problematic: when we decide we want a peer, we don't want to wait for anything) instead of just implementing the forced slot taking _without_ a future involved. Again, the feature that we want is not "let's kick peers until we have room". The feature is: "let's connect to a useful peer regardless of current connection count, within reasonable limits that don't exhaust some system resource like file descriptors.

**Comment by arnetheduck** [comment]
> libp2p clearly lacks the ability to give control over incoming connections to applications,

the alternative is that the application gets an async callback (akin to a gossipsub message validator) that waits until conditions are right to allow _one_ more peer - this effectively is the same as moving the semaphore into the application, except less opinionated - basically, libp2p now doesn't have to bother with peer counts at all - it's fully in the domain of the application - it decides whether to dial and it decides whether to open up slots for incoming connections.

**Comment by Menduist** [comment]
This issue was implemented (slightly tweaked) here: https://github.com/status-im/nimbus-eth2/pull/3346
