### ISSUE TITLE
Implement optimized history traversal in the REST API

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#3129]
A common usage pattern of the REST API is to traverse the entire history of the beacon chain by requesting epoch or slot information one step at a time (i.e. using increasing consecutive numbers). At the moment, this would be very expensive as each requests will go through the motions of loading and replaying the same blocks over and over again.

A simple caching mechanism can make our API significantly faster:

1) Each time an old state is restored from the database, we can keep it around for a certain amount of time (e.g. 10 seconds, a configurable value).

2) When another requests comes it, we take a look whether some of our existing cached states can be advanced cheaply to satisfy the requests (i.e. we can define a maximum slot/epoch difference to be considered a cheap match).

3) We use the existing lower-level APIs of the DAG to advance the cached state (e.g. `updateStateData`) and serve the request.

Practical issues:

The `updateStateData` function needs some minimal modifications to make this work - it needs to consider its `state` parameter as input/output and enhance its "UpdateStateData cache miss" path to consider the input state as a possible starting replay point. This would require some care at the existing call-sites that reuse existing state objects such as `dag.epochRefState` and may assume that `state` is a pure output parameter. Alternatively, we can just extract the replay logic from `updateStateData` into another reusable function.

Security considerations:

If the cache in unbounded, a rogue user of the API may exhaust the system resources by requesting different states. We can mitigate this by simply bounding the size of the cache to a configurable value with a reasonable default (e.g. 10). It is unlikely that typical users will run that many concurrent history traversals.

**Comment by arnetheduck** [comment]
It's actually more simple than that: on the first rest API request, we can allocate a beacon state that we keep reusing just for the rest api, just like we reuse the current states for specific purposes - this division of states is here because there's no way in nim to track ownership, and we've had numerous bugs because one use of the state overwrites another.

re `updateStateData`, it has some primitive logic to compute the "cost" of a replay, so it should automatically reuse the "closest" `BeaconState` it knows of (ie there's several costs it can roughly anticipate - state load, block load, epoch switch and so on) - this should be trivial to extend in any direction.

That said, it's also slightly questionable as far as features go - ie there are two kinds of requests: pre-finality and post-finality - the post-finality requests are pretty fast no matter what because we keep every epoch in the database and it's actually not that expensive to reload (of course, it's a cost).

Pre-finality requests should generally neither be used nor be necessary on a beacon node with live validators, and we should really block them by default, and require a flag to enable historicals as well.

As far as features go, the `StateDiff` feature will make state transitions cheap and storage efficient - that's probably a better approach overall, looking at cost/benefit (it should reduce database size as well).

Finally, the rest API today does far too many replays to begin with: it should not be replaying for several requests that are trivially implementable without a replay - always replaying is a simple starting point, but before we make new caches, we should exploit the cache-less optimizations because these will always be a lot cheaper.

**Comment by zah** [comment]
I should have clarified that the cache I'm suggesting is owned by the REST service indeed. The purpose of having multiple states and the expiration mechanism is to:

1) Reduce memory once the traversal is over
2) Support multiple concurrent traversals

Otherwise, while it's possible to implement this feature in other ways in the future, the path described here is a small incremental addition over what we have right now and one that can be delivered quickly, allowing key beacon node users such as block explorers to benefit from the functionality as soon as possible.

**Comment by arnetheduck** [comment]
sure - if we do it that way, it's actually quite simple - from my points above, the minimal change is likely that the logic for scoring replays needs revisiting for pre-finality states - it's quite dumb right now.
