### ISSUE TITLE
[RFC] Reduce the need of shell scripts

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#343]
The amount of shell script is growing in the repo. This makes understanding the build system much more complex for first-time contributors and people who would like to submit a simple fix.

**Comment by tersec** [comment]
Additionally, it results in a more fragile-by-default build system sensitive to details of path elements and with increased risk of unintended deletion of files in such scenarios given such unexpected pathnames.

**Comment by stefantalpalaru** [comment]
That's like saying "reduce the amount of code to facilitate understanding". True, but irrelevant.

What's the alternative to those shell scripts you deem redundant?

**Comment by arnetheduck** [comment]
We've discussed this at the offsite and come to the conclusion that it's time to move the build system to its own repo and make `nim-beacon-chain` a top level repo with its own `vendor` structure.

The objective is to make the repo "feel" closer to what it will look like when a package manager is in place by having a top-level makefile for every "application" we have (vs libraries like stint) and manage the dependencies from the application itself instead of the slightly convoluted practice we have now.

Essentially, the "main" project should have a custom Makefile that includes select parts of the build system, and everything is locked down with submodules just like the `nimbus` repo is today.
