### ISSUE TITLE
Revisit #3893 (avoid packing attestations from other forks)

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#4014]
Since the [linked PR](https://github.com/status-im/nimbus-eth2/pull/3893) was reverted due to increased CPU usage, we need to investigate alternative solutions for the problem being solved.

**Comment by arnetheduck** [comment]
To avoid the signature check, what instead should be done is to ensure that the attestations being added to the block share dependent root (and thus shuffling) with the block itself: this is done by ensuring that the block and attestation target shares a common ancestor at the attestation `((attestation.data.target.epoch - 1).start_slot - 1)` slot - the logic is the same as for the shuffling cache and REST API dependent root lookup for attestation duties - care must be taken because attestation.target.epoch spans 2 epochs for valid attestations.

**Comment by arnetheduck** [comment]
https://github.com/sigp/lighthouse/blob/aab4a8d2f2c13238293700712a39bca98dec2964/beacon_node/beacon_chain/src/beacon_chain.rs#L1981 - corresponding logic in lighthouse
