### ISSUE TITLE
Refactor crypto.nim, BlsValue / OpaqueBlob

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#412]
With the workaround for OpaqueBlobs in deposits #408 and zero signature in #374, crypto.nim is becoming messy.

Also changing BlsValue default to OpaqueBlob is needed.
Ideally we should lazily convert blobs to real BlsValue instead of at parsing to limit startup costs if loading from say thousands of JSON files or a DB.

**Comment by mratsim** [comment]
See https://github.com/status-im/nim-beacon-chain/pull/457

Since it was abandoned for the time being we need at least a fix for BLS default initialization

**Comment by tersec** [comment]
Since other recent performance improvements, with `beacon_node` in `-d:release` in a local network sim with 1000+ validators total, exactly as suggested here simply reading via
https://github.com/status-im/nim-beacon-chain/blob/752369b6bb72d118f91a5529ddf689109fefef1d/beacon_chain/block_pool.nim#L476-L481
calling ultimately into `spec/crypto.nim` and `nim-blscurve` to initialize via `setx` an SSZ object whose `BlsValue`s it doesn't need to keep re-verifying, eager blob to BlsValue conversion is now 25% of total runtime according to `perf`, the 2nd largest single identifiable time usage source.
