### ISSUE TITLE
Cannot create non-wall-slot block proposal

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4181]
Here we see an attempt to create a block for `3975925` while head is at `3975927` - this should not be an invalid operation given that 25 has not finalized yet:

```
INF 2022-09-26 21:05:31.134+02:00 State replayed                             topics="chaindag" blocks=15 slots=18 current=94282677:3975927 ancestor=a923334c:3975903@3975904 target=fabbf676:3975922 ancestorStateRoot=08822ff0 targetStateRoot=5403b0d6 found=false assignDur=47ms478us146ns replayDur=608ms552us126ns
ERR 2022-09-26 21:05:31.146+02:00 Engine API fork-choice update failed       topics="beacval" err="{\"code\":-38003,\"message\":\"Invalid payload attributes\",\"data\":{\"err\":\"invalid timestamp, parent 1664219124 given 1664219076\"}}" finalized_block_hash=1df2bf99 head_block_hash=07b54e4f
INF 2022-09-26 21:05:31.172+02:00 getExecutionPayload: newExecutionPayload invalid topics="beacval" executionPayloadStatus=ok(INVALID_BLOCK_HASH)
WRN 2022-09-26 21:05:31.173+02:00 Unable to get execution payload. Skipping block proposal topics="beacval" slot=3975923 validator_index=271550
```

321c87279050d6f4f2014f2c81731bb4835cd26d - this results from a call to the proposer rest api:

http://localhost:5052/eth/v2/validator/blocks/3975925?randao_reveal=0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&skip_randao_verification

**Comment by tersec** [comment]
The EL is apparently rejecting this block. The fix, such as it is, would be to remove
https://github.com/status-im/nimbus-eth2/blob/ad286b9aadf25c995294aa96e8c6408a747912b2/beacon_chain/validators/validator_duties.nim#L424-L429

However, it was added initially because otherwise back-to-back blocks being proposed by the same node weren't being registered with the EL, i.e. the first block was proposed, but the EL never learned about its payload via any other means from the CL (and EIP-3675 prohibits post-merge EL block gossip), so the second block was not successfully produced, either not at all or with incorrect EL-parent-block.

More recently, it's been a useful safeguard that the empty execution payload blocks are verified to be actually correct before being sent out.

So if the first issue has been since otherwise resolved via the overall block flow ensuring that the block processor sees all the blocks, including those proposed by the node itself, in time for the second block to be produced (because it's an asynchronous queue, not known how long it is), then the first issue might be moot.

The second issue can be either stipulated to be a question of debugging/having other safeguards or just finding out via other nodes that Nimbus empty-payload-blocks are correct.

A final issue is that dealing with external block builders, it's good to have similar safeguards too -- to have a local EL verify the block isn't random garbage. It's too late to do anything about it without risking slashing, but at least avoid sending garbage to the network.

So this ends up being a function of how one prioritizes those and what the spec-intended flow, including incorporating the EL checks (weird it returns `INVALID_BLOCK_HASH` for `invalid timestamp`, but https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#specification confirms this is correct).

https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#specification-1 states that:
> 7. Client software **MUST** ensure that `payloadAttributes.timestamp` is greater than `timestamp` of a block referenced by `forkchoiceState.headBlockHash`. If this condition isn't held client software **MUST** respond with `-38003: Invalid payload attributes` and **MUST NOT** begin a payload build process. In such an event, the `forkchoiceState` update **MUST NOT** be rolled back.

So it seems to be acting within specifications as well here.

**Comment by arnetheduck** [comment]
> The EL is apparently rejecting this block. The fix, such as it is, would be to remove

can't the timestamp be fixed? hm, I guess we perhaps would have to fCU to the parent so that we can create such blocks - might not be worth it.


> However, it was added initially because otherwise back-to-back blocks being proposed by the same node weren't being registered with the EL, i.e. the first block was proposed, but the EL never learned about its payload via any other means from the CL (and EIP-3675 prohibits post-merge EL block gossip), so the second block was not successfully produced, either not at all or with incorrect EL-parent-block.
> 
> More recently, it's been a useful safeguard that the empty execution payload blocks are verified to be actually correct before being sent out.
> 
> So if the first issue has been since otherwise resolved via the overall block flow ensuring that the block processor sees all the blocks, including those proposed by the node itself, in time for the second block to be produced (because it's an asynchronous queue, not known how long it is), then the first issue might be moot.

This is the case regardless of EL - we can't create a block with the correct CL parent until it has gone through the complete pipeline, which includes posting the block to the EL.

> The second issue can be either stipulated to be a question of debugging/having other safeguards or just finding out via other nodes that Nimbus empty-payload-blocks are correct.

Same as state transition: we should send out block as soon as it's gossip-valid, which doesn't include execution - this allows the block to optimistically propagate earlier at no penalty if it's wrong.

> A final issue is that dealing with external block builders, it's good to have similar safeguards too -- to have a local EL verify the block isn't random garbage. It's too late to do anything about it without risking slashing, but at least avoid sending garbage to the network.

Ditto - it's better to send gossip-valid stuff optimistically because there's no penalty and potential benefit (in terms of getting the block voted for)

**Comment by etan-status** [comment]
fcU to ancestors is allowed to be ignored by the EL. It will say `VALID` and return the `latestValidHash` it has.

**Comment by etan-status** [comment]
> Client software MAY skip an update of the forkchoice state and MUST NOT begin a payload build process if forkchoiceState.headBlockHash references an ancestor of the head of canonical chain. In the case of such an event, client software MUST return {payloadStatus: {status: VALID, latestValidHash: forkchoiceState.headBlockHash, validationError: null}, payloadId: null}.

https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#engine_forkchoiceupdatedv1

**Comment by tersec** [comment]
Using fcU to fix the timestamp would require more coordination between `validator_duties` and `block_processor` than exists, to micromanage the state this way. It would be interact in a fragile way with the asynchronous setup currently used.

**Comment by tersec** [comment]
If the other cases just aren't a concern, the simpler approach is to remove `newPayload` from the validator flow entirely. But that change needs to be tested a decent amount, especially with regard to these consecutive block proposals.

**Comment by arnetheduck** [comment]
> If the other cases just aren't a concern, the simpler approach is to remove newPayload from the validator flow entirely. But that change needs to be tested a decent amount, especially with regard to these consecutive block proposals.

yes, I think that's the right thing to do here, irrespective of the timestamp issue

**Comment by tersec** [comment]
> > If the other cases just aren't a concern, the simpler approach is to remove newPayload from the validator flow entirely. But that change needs to be tested a decent amount, especially with regard to these consecutive block proposals.
> 
> yes, I think that's the right thing to do here, irrespective of the timestamp issue

https://github.com/status-im/nimbus-eth2/pull/4186

**Comment by arnetheduck** [comment]
We're good here - non-head slots aren't a real use case and the remaining discoveries in this ticket have been addressed
