### ISSUE TITLE
[Test net] Empty block proposed?

### ISSUE THREAD

**Issue by gus4rs** [status-im/nim-beacon-chain#4198]
One of my validators on testnet proposed a block with zero transactions.

I am wondering if this is a bug on nimbus or maybe misconfiguration, since it seems most (if not all) blocks on goerli are non-empty.

I'm on the latest version of both nimbus and erigon, and haven't found anything unusual in the logs.

**Comment by zah** [comment]
Have you preserved any logs from the time immediately before the block proposal?

If there is a communication problem with the execution layer, Nimbus would use a fallback strategy of producing an empty block because this is still better than missing the proposal slot altogether. When this happens, there is a specific warning or error log message indicating the observed problem:

* warning: getExecutionPayload: eth1Monitor not initialized; using empty execution payload
* warning: Getting execution payload from Engine API timed out
* warning: Getting execution payload from Engine API failed
* error: Error creating non-empty execution payload; using empty execution payload

**Comment by gus4rs** [comment]
As I pointed out earlier, no errors or warnings were found in the logs.

**Comment by zah** [comment]
Then I would check the peer-to-peer network connectivity of the execution layer node. If the node is not connected to the traditional DevP2P network of Ethereum 1.0, it won't receive any broadcasted transactions and its mempool will remain empty which in turn will result in empty block proposals.

If you are running Geth for example, you can check the number of network peers by running `geth attach` and then entering `net.peerCount` in the console.

**Comment by gus4rs** [comment]
I proposed another block and it came with transactions now! I also added a new param **txpool** param to Erigon (my execution client) to be able to see pending transactions using curl (without it, it was coming out empty)

```
curl -X POST -H "Content-Type: application/json" --data '{"method": "txpool_content", "params": [], "id":1}' localhost:8545 
```

```
--http.api=eth,debug,net,txpool,trace,web3,erigon,engine
```

**Comment by arnetheduck** [comment]
Closing as this seems to have been a configuration error on the EL side - do reopen if it happens again
