### ISSUE TITLE
Use new block value API

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#4243]
https://github.com/ethereum/execution-apis/issues/307 allows simple value discovery - we should use it to compare with builder blocks.

**Comment by tersec** [comment]
Sure, is it supported by enough ELs yet?

It would enable https://github.com/status-im/nimbus-eth2/issues/4084 for example, without requiring `nimbus-eth2` to independently simulate execution payloads' transactions.

**Comment by arnetheduck** [comment]
@MariusVanDerWijden is apparently working on it for geth

**Comment by tersec** [comment]
https://github.com/flashbots/mev-boost/pull/274 supports a slightly different, mostly-equivalent approach.

**Comment by allboxes** [comment]
> [flashbots/mev-boost#274](https://github.com/flashbots/mev-boost/pull/274) supports a slightly different, mostly-equivalent approach.

This is more of a stop-gap since MEV-Boost doesn't have access to the locally built block (or it's value). In other words it's just a fixed minimum value required for MEV-Boost to pass along a relayed block.  

With the current architecture MEV-Boost would need access to the payload from the local EL to enable the local/remote value discovery to happen in MEV-Boost.

ETA: I may have misread your post, the MEV-Boost feature is equivalent to #4084, but does not use the block value API to enable value discovery.

**Comment by arnetheduck** [comment]
> With the current architecture MEV-Boost would need access to the payload 

Regardless, this would place a little bit too much responsibility on mev-boost - it's better that we keep this in nimbus so that if mev-boost fails for whatever reason, we still have a direct line to the EL.

**Comment by zah** [comment]
We now make use of the `blockValue` field in the EL responses when working with multiple EL nodes. When the EL doesn't indicate the block value, we calculate it ourselves from the list of transactions. Currently, there is no comparison between the value of blocks produced by the ELs or the Builder API (the Builder is assumed to produce more valuable blocks). We are likely to change this in the future.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4795
