### ISSUE TITLE
Split Nimbus guide out into a separate repository

### ISSUE THREAD

**Issue by tavurth** [status-im/nim-beacon-chain#4275]
**Is your feature request related to a problem? Please describe.**
As a developer I would like quick and easy access to the documentation. Coming to [nimbus.guide](https://nimbus.guide/developers.html) everytime works, but if I have the files in markdown (generated is also ok) then I can read them directly from emacs.

This becomes a 2 key combo to swap to documentation and search inside of it, instead of having to use Github or other web based service.

**Describe the solution you'd like**
I would like to see the documentation split into a separate repository if possible. It could be linked here as a subtree if required.

If the documentation is generated (I will look into this part now), I would expect a output folder to be included or easily generated.

That way I can search from my local machine.

**Describe alternatives you've considered**
I use Godot a lot for my development, and the built-in documentation there is probably one of the best developer workflows I've come across.

**Additional context**
N/A

**Comment by tersec** [comment]
Could you clarify what you mean by "Nimbus style guide"? https://github.com/status-im/nim-style-guide/ is already a separate repository, with Markdown source, and https://status-im.github.io/nim-style-guide/ is a browseable HTML form which is also separate from `nimbus-eth2`.

**Comment by tavurth** [comment]
Yep that should be `nimbus.guide` not `Nim style guide`

**Comment by arnetheduck** [comment]
The nimbus guide source lives here: https://github.com/status-im/nimbus-eth2/tree/unstable/docs/the_nimbus_book - because it's coupled tightly with features in the project itself, it should stay in the same repo - `nimbus.guide` itself is also intended for a general audience _using_ Nimbus - more details about developing nimbus-eth2 itself go directly to https://github.com/status-im/nimbus-eth2/tree/unstable/docs and not `nimbus.guide` (the latter being just a light introduction for users like packagers and third-party integrators)
