### ISSUE TITLE
Wrong amount of threads used.

### ISSUE THREAD

**Issue by GranderStark** [status-im/nim-beacon-chain#4341]
**Describe the bug**
Passing `num-threads` 2 renders threads used by nimbus to 4. Passing `num-threads` 3 renders threads used by nimbus to 5.
Is it intentional?

**To Reproduce**
1. Docker image `statusim/nimbus-eth2:amd64-v22.10.1`
2. `cat /proc/1/status | grep -i threads`

**Additional context**
Could we assume, that first thread is used for spawning other threads? Then why we have this "+1" thread? What is it doing?

**Comment by arnetheduck** [comment]
The `num-threads` argument indeed represents the number of additional "computation" threads that we start - there is a separate "utility" thread indeed, but looking at CPU usage, it would perhaps make sense that we adjust the num-threads down one so that a value of 2 results in 2 "heavy" threads and not 3, as currently happens.

Good catch!

**Comment by zah** [comment]
This deserves mentioning in a potential extended manual for Nimbus, but it's probably a bit too much of a technical detail to mention in the regular Nimbus guide, so I'm closing this issue for now.

**Comment by GranderStark** [comment]
@zah please mention this in nimbus guide, because nimbus has problems with usage more than one core on the load after sync is finished. It is unable to stay synced under the load.
That will lead to same investigation and same question, so it's good to know, what behaviour is expected at least at the point of threads usage.
