### ISSUE TITLE
always NULL result when call API light_client/bootstrap/{block_root}

### ISSUE THREAD

**Issue by xichan-ms** [status-im/nim-beacon-chain#4453]
I have run a beacon node, everything seems good, and light client related APIs except the following one work well, so weird.

However, when call API light_client/bootstrap/{block_root}, **always get null result**, such as 

```
curl http://localhost:5052/eth/v0/beacon/light_client/bootstrap/0xfe37dd9a568a6f5e7a8707f66f703cd0f323cc14f1224b88a99eb43130bb9f87
```

I started the node with following command,

```
./run-prater-beacon-node.sh --web3-url=http://127.0.0.1:8551 --rest --jwt-secret=/tmp/jwtsecret --light-client-data-serve --light-client-data-import-mode=on-demand --light-client-data-max-periods=999999
```

**Is there any configuration that I missed? or this API is not supported at all?**

BTW, same phenomances for these examples APIs in page https://nimbus.guide/rest-api.html

**Comment by etan-status** [comment]
In your example, the query is referring to an outdated version. If you use `v1` instead of `v0` in the URL, it should work. See https://github.com/ethereum/beacon-APIs/blob/5531223863459cc44df73d5d96929a40684935ac/beacon-node-oapi.yaml#L108

Also, a `null` result is unexpected; are you referring to the HTTP 404 status code?

**Comment by xichan-ms** [comment]
@etan-status thanks a lot, change to v1 works! help a lot, really appreciate it.
