### ISSUE TITLE
Optional support for providing fee recipient information to the remote Web3Signer node

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#4741]
Certain Web3Signer implementations (such as the one used by the [Diva protocol](https://divalabs.org/)) wish to validate that the blocks that they are signing have a certain expected fee recipient value.

We can support this use case by providing an extra field in the `/api/v1/eth2/sign/{identifier}` request, storing a SSZ merkle proof for the fee recipient value that will be rooted in the signed block root. To make the protocol more general, the new field can store a list of generalized indices with their matching merkle proofs (this will allow more complex pre-signing validation schemes by interested implementations).

Since this is an extension of the Web3Signer protocol, we should leverage the `remoteType` field of our remote keystore format to indicate the use of the custom protocol (e.g. we can call the extension `DivaSignerV1`).

We will validate the soundness of the protocol extension by adding support for it in our in-house Web3Signer implementation (currently used only for testing). The final scheme will be proposed as an upgrade to the Web3Signer protocol if there is wider interest in the community.

**Comment by pradavc** [comment]
Introducing generalized indices is a great idea. Most of the fields that applications could use (and the fee recipient field in particular) are two levels below the `body_root`, which is what we get with the [current spec of the Web3Signer API](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Signing/operation/ETH2_SIGN). 

Since the W3S API cannot request to the validator anything, how do you plan on defining the different fields that could be sent? Setting a flag at launch that enables a selection of fields for the W3S?

**Comment by zah** [comment]
This protocol extension has been implemented and documented here:
https://nimbus.guide/web3signer.html#verifying-web3signer
