### ISSUE TITLE
Crosslink issue

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#482]
After a time on the eth2 simulation we trigger one of the following crosslink message:

https://github.com/status-im/nim-beacon-chain/blob/5f271fd82e3b3093fa293c3171ccf62fa34d8009/beacon_chain/spec/beaconstate.nim#L567-L570

https://github.com/status-im/nim-beacon-chain/blob/5f271fd82e3b3093fa293c3171ccf62fa34d8009/beacon_chain/spec/beaconstate.nim#L577-L580

**Comment by tersec** [comment]
This should not be prioritized, as https://github.com/ethereum/eth2.0-specs/pull/1428 is approved and will remove crosslinks from phase 0, unless it critically breaks a near-term testnet rather than warning.

If it's an indicator for some other underlying/more fundamental issue, fine, but if it's genuinely solely a crosslink management issue which stays somewhat isolated, spending too much time on this is a bad investment.

**Comment by tersec** [comment]
https://github.com/ethereum/eth2.0-specs/releases/tag/v0.9.0 removes crosslinks from phase 0.
