### ISSUE TITLE
cp: cannot stat 'v0001800.privkey': No such file or directory

### ISSUE THREAD

**Issue by ulikestyle** [status-im/nim-beacon-chain#483]
when i run this command
`./tests/simulation/run_node.sh 9`

error like this
`[Nimbus env] 0 Thu Oct 10 18:22:31 |~/eth2.0/nim-beacon-chain|
root$ ./tests/simulation/run_node.sh 9
cp: cannot stat 'v0001800.privkey': No such file or directory
cp: cannot stat 'v0001801.privkey': No such file or directory
cp: cannot stat 'v0001802.privkey': No such file or directory
cp: cannot stat 'v0001803.privkey': No such file or directory
cp: cannot stat 'v0001804.privkey': No such file or directory
cp: cannot stat 'v0001805.privkey': No such file or directory
cp: cannot stat 'v0001806.privkey': No such file or directory
cp: cannot stat 'v0001807.privkey': No such file or directory
cp: cannot stat 'v0001808.privkey': No such file or directory
cp: cannot stat 'v0001809.privkey': No such file or directory
cp: cannot stat 'v0001810.privkey': No such file or directory
cp: cannot stat 'v0001811.privkey': No such file or directory
cp: cannot stat 'v0001812.privkey': No such file or directory
cp: cannot stat 'v0001813.privkey': No such file or directory
cp: cannot stat 'v0001814.privkey': No such file or directory`

**Comment by zah** [comment]
I suspect this has happened because the supplied node index parameter to `run_node.sh` (9) was out of the valid range. The following two variables determine what the valid indices are:

https://github.com/status-im/nim-beacon-chain/blob/5f271fd82e3b3093fa293c3171ccf62fa34d8009/tests/simulation/vars.sh#L17-L18

In order for you to be able to use `run_node.sh` like this, there must be at least one missing node. Currently, the first `NUM_NODES` indices starting from 0 will be used by the node launched from `start.sh` script and the following `NUM_MISSING_NODES` are up for grabbing.

We can improve the run_node script by printing an appropriate error message in this situation. We can also place the missing nodes at the indices near zero to make the feature easier to use in general.

**Comment by arnetheduck** [comment]
actually our readme is wrong here - it still recommends run_node 9 but that's not the default setup in `vars.sh`
