### ISSUE TITLE
run and control a testnet locally

### ISSUE THREAD

**Issue by zah** [status-im/nim-beacon-chain#547]
We could benefit from the ability to run local network simulations in long-running sessions where some of the nodes can be temporarily stopped and restarted at will. This will more closely resemble the real-world setup where nodes can crash, join the network at arbitrary times, experience temporary connection outages and so on.

To achieve this, we can develop a very simple "supervisor" script/program that is in charge of running a single node. Running this program under Tmux will allow us to interact with it with the keyboard in order to issue commands such as:

1. Stop this node
2. Restart this node
3. Cut off this node from the network (optional, maybe available only on select OSes that make this easy)

Furthermore, running in Tmux will allow the developers to launch long-lasting network simulations on servers within the Nimbus testnet cluster and then connect from a node on their own computer thought the `bootstrap_nodes.txt` file created by the simulation scripts (we'll need to dedicate an open port range for this purpose). It should also improve the terminal emulation required for features such as the beacon node status bar.

One candidate for the supervisor program is the [nim-chronicles-tail](https://github.com/status-im/nim-chronicles-tail) tool, which offers a prompt where the described commands can be entered. Using chronicles tail will also allow us to add interactive log search and filtering functionality in the future.

The described supervisor/tailing setup can be compatible both with the regular builds of the beacon-node that we use now as well as with docker builds that will more closely match the conditions of the real testnets.

**Comment by stefantalpalaru** [comment]
I think Zahary's proposed UI looks something like what you get in `make USE_MULTITAIL=yes eth2_network_simulation`, but with interactive shells running in each of those little virtual terminals, like in [Cluster SSH](https://www.topbestalternatives.com/wp-content/uploads/2015/12/ClusterSSH.jpg).

![multitail](https://i.imgur.com/1l7fIol.png)

I see it closer to top/htop showing only beacon_node instances and having custom actions:

![htop](https://i.imgur.com/SNks9Kt.png)

I also don't want to show logs, but to save them on disk for later. I'm usually interested in node status, not the Matrix scrolling by. If something goes wrong, I can go read the separate log.

This setup is meant as a debugging aid. The initial question was: what happens when a node loses network connectivity for a while and then tries to catch up? This boils down to: I want to apply a certain action to a certain node, wait a few minutes, apply another action and see what happens.

**Comment by zah** [comment]
Well, the scrolling matrix, even if unreadable, acts as a sort of oscilloscope for the beacon node. It's not a bad status indicator especially if the status bar works as intended. My original idea was that we'll spend only few hours here to implement something quick and dirty (with tmux and a custom supervisor such as chronicles tail). Having a scriptable simulation orchestrator is certainly good for automated testing, but it wouldn't be wise to spend too much time on developing a sophisticated UI for it.

**Comment by stefantalpalaru** [comment]
Debugging this complex testnet is a long-term endeavour. We'll be doing it for the foreseeable future, so why improvise the local setup?

> Having a scriptable simulation orchestrator is certainly good for automated testing

Bingo! After we fix a buggy scenario, we'll want reproducibility and testing for it. It's unavoidable.

**Comment by arnetheduck** [comment]
generally, to test "cut off from network" you don't need to run a full simulation with N nodes - you need two, one on the rasperry sitting next to you, from which you unplug the cable - or possibly inside a docker, from which you do `if down` or whatever the command is to shut down the bridge. it's.. very simple if you want it to - building a ui for debugging some simple scenario seems a bit overkill, specially since we don't envision our users using this (it's not an expected setup to run more than one node on a single machine).

if instead we start with data being exported, then the ui can be built as a separate process that connects via RPC - locally or remote - I suggest we focus on exporting a good API if we want this functionality - then our users can use the same setup as us to control their nodes (and running multiple on a single machine becomes a special case that we use during development).

crucially, we can then build it flexibly: web, a plugin to https://nicolargo.github.io/glances/ or something else.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/682 begins implementing this.

**Comment by mratsim** [comment]
Solved by #682 and also @sinkingsugar work on multinet scripts, it includes Lighthouse and Prysm nodes: https://github.com/eth2-clients/multinet/pull/6
