### ISSUE TITLE
[SSZ] List support is hacky

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#557]
This is blocking #518.

On 0.8.1 we had no List type in the spec (except 1 iirc) however 0.9.1 generalizes List types with max length.

On hashTreeRoot compute, you currently are required to call `sszList` instead of Nim automatically inferring that need from the List type.
Unfortunately this is not possible when hashing a container such as IndexedAttestation.

The List type should be changed to a distinct or an object.

Test case:

#### Python
```python
# taken from eth2specs
from pyutils.ssz.ssz_typing import uint64, List
from pyutils.ssz.ssz_impl import hash_tree_root

MAX_VALIDATORS_PER_COMMITTEE = 2048

x = [0, 0, 0, 0, 0]

x = List[uint64, MAX_VALIDATORS_PER_COMMITTEE](x)
print(x)
print(hash_tree_root(x).hex())
```
```
List[uint64, 2048](0, 0, 0, 0, 0)
cdf8faf4d18864e29a8dc7f7530e235654f1388afea3d35f4ef5200b2a45829b
```

#### Nim
```Nim
import ../beacon_chain/ssz
import ../beacon_chain/ssz/types
import stew/byteutils

const MAX_VALIDATORS_PER_COMMITTEE = 2048

let x = @[0'u64, 0, 0, 0, 0]
echo x.hashTreeRoot().data.toHex()

block:
  echo "-----------------------------------------------"
  let y = List[uint64, MAX_VALIDATORS_PER_COMMITTEE](x)
  echo y.hashTreeRoot().data.toHex()

block:
  echo "-----------------------------------------------"
  echo sszList(x, int64 MAX_VALIDATORS_PER_COMMITTEE).hashTreeRoot().data.toHex()
```
```
c18ec0eb35b9e9e2f605bc362f6783d5975641a71ad2dad05a79e40421e5fb32
-----------------------------------------------
c18ec0eb35b9e9e2f605bc362f6783d5975641a71ad2dad05a79e40421e5fb32
-----------------------------------------------
cdf8faf4d18864e29a8dc7f7530e235654f1388afea3d35f4ef5200b2a45829b
```

**Comment by mratsim** [comment]
Only a couple of changes are needed to switch to a distinct type but it does not magically fix the SSZ hashTreeRoot issues: https://github.com/status-im/nim-beacon-chain/commit/e2dc41dd6fdd388dc13029ed83e2e932c00697a2

The absence of borrow for generic distinct is a pain to work around with https://github.com/nim-lang/Nim/issues/2684.

Furthermore distinct seems to be one of the less supported Nim features (even compared with static) and their interaction with generics might lead us to a dead end:
- can't for loop with distinct generic: https://github.com/nim-lang/Nim/issues/12086 (prevents from using a distinct Slot
- distinct pointers coercion: https://github.com/nim-lang/Nim/issues/7165

On the other hand, keeping the status quo and updating the following macro is also buggy:
https://github.com/status-im/nim-beacon-chain/blob/6f2d980bff28153672ae79ba5c9f3ff091848b58/beacon_chain/spec/datatypes.nim#L349-L378

This leads to very obscure type issue when BeaconChainDB tries to serialize BeaconState and historical_roots (List[Eth2Digest, HISTORICAL_ROOTS_LIMIT]) and eth1_data_vote (List[Eth2Digest, SLOTS_PER_ETH1_VOTING_PERIOD]) are conflated into the same type, probably because both are resolved into seq[Eth2Digest]

![DeepinScreenshot_select-area_20191118155213](https://user-images.githubusercontent.com/22738317/69063058-1f607a80-0a1c-11ea-84d9-3f500ba509b7.png)

**Comment by mratsim** [comment]
And actually, SszType seems to get stuck on a type. Changing the order of the "when" to dispatch Lists first now gives issue on ETH1Data:
![DeepinScreenshot_select-area_20191118162844](https://user-images.githubusercontent.com/22738317/69065882-b92a2680-0a20-11ea-974c-c9ed56ea20a9.png)

Interestingly, both `List[Eth2Digest, HISTORICAL_ROOTS_LIMIT]` and `Eth1Data` are from the fields directly before `List[Eth2Digest, SLOTS_PER_ETH1_VOTING_PERIOD]` with SLOTS_PER_ETH1_VOTING_PERIOD == 16 and HISTORICAL_ROOTS_LIMIT == 16777216

**Comment by mratsim** [comment]
Those bind-once bind-many / dependent-types issues are probably what is also blocking the ComplexTestStruct SSZ test mentionned in https://github.com/status-im/nim-beacon-chain/pull/522#issue-337312433

**Comment by zah** [comment]
As you have stated in the original description, if using distinct seq types turns out to be too problematic, we can always go with an object type holding a single `seq` field. 

I'm not sure I understand what you mean when you say "bind-once bind-many / dependent-types issues". I wouldn't put these issues in the same category in general. Would you like me to help with debugging the problems in the distinct branch?

**Comment by mratsim** [comment]
For now I've opened a PR without distinct as using distinct created regressions.
I think the object that holds a seq is probably the one that will encounter the less bugs in the future.

I have to revisit the bind-once/many things because I made a mistake in my definition of `eth1_data_votes`, it should have been a `List[Eth1Data, 16]` and not `List[Eth2Digest, 16]`

**Comment by mratsim** [comment]
In the future, I think a macro could actually be simpler than all the switch on the various static types, especially because we could just dump the code with `repr` or `toStrLit` while at the moment we have to instantiate it in our head. See comment in: https://github.com/status-im/nim-beacon-chain/pull/566

**Comment by zah** [comment]
I'm not sure I understand the macro proposal. Are you suggesting a macro that uses `getType` and friends to generate the correct serialization code for composite records?

**Comment by mratsim** [comment]
I think it can just be a recursive getTypeImpl, I have bad memories with getType and working with generics in macros :P.

**Comment by zah** [comment]
I'm very doubtful that something based on `getTypeImpl` would be an improvement. There are several reasons for this:

1) Overload-based APIs are required for teaching the library about user types. Since the macro system intentionally doesn't have access to the scope system, it cannot check whether the user scope has definitions that override any behavior in the library.

2) Type comparison in macros is extremely hard to do because Nim has very complex rules for type equality in the presence of alias types, generics and all that jazz. Re-implementing the overload selection and the `is` operator there will be a very uphill battle.

3) The current code is easier to instrument (i.e. it makes it easy to selectively add tracing at run-time). For me, this is the real debugging when in comes to SSZ. It took a while to get our implementation to agree in the hashing rules of the spec.

4) You have to take a single look at the code behind `getCustomPragma` in Nim's macros modules to get a preview of what a mess will expect us with a solution based on `getTypeImpl`.

-----------

All of the above arguments are usually summed up in the simple rule of thumb "use the least powerful construct that gets the job done" - in this case, generics with some templates for inlining the simpler rewrites. Before someone argues that an even simpler implementation is possible if we don't rely on nim-serialization and faststreams, I would say that for me this would have failed in the "gets job done" department, but this is a longer discussion that I would like to avoid now.

"Executing templates and functions in one's head" is something you do all the time when you deal with any code. If the code is factored in composable and easy-to-understand smaller abstractions, you don't need to understand every detail all the way down. You just have to learn why a template such as `valueOf` exists and what kind of result it produces.

I do agree that Nim adds a lot of unwanted accidental complexity due to the poor error messages and implementation bugs that make these abstractions leaky, but that's what we have now. It can be improved if we take the time to file issues and advocate for improvements. FWIW, I've put some effort to improve the error messages with special helpers such as [unsupported T](https://github.com/status-im/nim-beacon-chain/blob/master/beacon_chain/ssz/types.nim#L69).

**Comment by arnetheduck** [comment]
there's now a `List[T]` and even a `HashList[T]` - amazing that it got past all the compiler bugs
