### ISSUE TITLE
[Fuzzing] Crash on nfuzz_attestation

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#659]
See the fuzzing input pinned in the fuzzing discord channel.

**Comment by arnetheduck** [comment]
attach files here, not version?

**Comment by gnattishness** [comment]
A bit annoying I can't attach the ssz directly:
[nim_attestation_crash.ssz](https://drive.google.com/file/d/1kvPkgUb6kyFXZ1NmnvGFM5j20nO7N8JO/view?usp=sharing)

This is a BeaconState + Attestation ssz container that, when passed to [`nfuzz_attestation`](https://github.com/status-im/nim-beacon-chain/blob/9050db7b95c7f072a8048cc0f955cbf2a2c5c9e1/nfuzz/libnfuzz.nim#L51), triggers the following assertion: 
[nim_attestation_trace.txt](https://github.com/status-im/nim-beacon-chain/files/4004230/nim_attestation_trace.txt)

**Comment by djrtwo** [comment]
I haven't investigated this scenario, but I assume this highlights a gap in our consensus tests.
Am I correct in that assumption?

Also, can someone add me to the fuzzing discord?

**Comment by gnattishness** [comment]
I think I've narrowed it down:
I can't see any equivalent in `nim-beacon-chain` for the following
`assert data.index < get_committee_count_at_slot(state, data.slot)` (https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attestations).

Because a larger index is allowed through, `index > count` is possible in `compute_committee`, and thus an `endIdx > index_count`.

**Comment by gnattishness** [comment]
@djrtwo I'm not certain re concensus tests, as this is effectively a "crash" of nim-beacon-chain, when it should return false (allowing nimbus to continue running).
If it's possible for the consensus tests to differentiate between an error return and a crash, then this could be a gap in the tests.

In pyspec, this would be triggering an AssertionError anyway. If the above understanding of the bug is correct, an equivalent bug in the pyspec would be for `assert data.index < get_committee_count_at_slot(state, data.slot)` to be missing from `process_attestation`, and the input triggers a different Assert in [`compute_shuffled_index`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#compute_shuffled_index):  `assert index < index_count`

Can someone confirm whether my understanding is correct?

**Comment by djrtwo** [comment]
Interesting, I see.

That said, this codepath is clearly not triggered in Nimbus during the consensus tests. It seems likely that we can and should craft a consensus test that would trigger this code path.

I'll monitor this thread and make a call when y'all post a fix

**Comment by tersec** [comment]
In theory, this should be fixed in `devel` now.

**Comment by tersec** [comment]
Feel free to re-open if this isn't, in fact, fixed.
