### ISSUE TITLE
cannot run any tests without getting ` Error: cannot open file:`

### ISSUE THREAD

**Issue by 0xalpharush** [status-im/nim-beacon-chain#6681]
**Describe the bug**
I can run make successfully but cannot run scripts or tests. I am not familiar with nim but try `nimball install`, `setup`, and `lock`. I'm not sure if it is some configuration, the lock file, or I am just passing the wrong command.

Eventually I get an error that this path `std/confutils` is wrong and the rest of the files don't prefix it with std
https://github.com/status-im/nimbus-eth2/blob/f54a0366abfba26c7694fad1e14350d19aa0a228/scripts/run_ssz_fuzzing_test.nims#L9-L9
**To Reproduce**
1. Platform details (OS, architecture): MacOS Apple Silicon 
2. Branch/commit used: 'f54a0366abfba26c7694fad1e14350d19aa0a228`
3. Commands being executed: 'make`
4. Relevant log lines: 

```
$ nim scripts/run_ssz_fuzzing_test.nims Attestation
Hint: used config file '/opt/homebrew/Cellar/nim/2.2.0/nim/config/nim.cfg' [Conf]
Hint: used config file '/opt/homebrew/Cellar/nim/2.2.0/nim/config/config.nims' [Conf]
Hint: used config file '/Users/x/nimbus-eth2/nim.cfg' [Conf]
Hint: used config file '/Users/x/nimbus-eth2/config.nims' [Conf]
/Users/x/nimbus-eth2/scripts/run_ssz_fuzzing_test.nims(1, 2) Error: cannot open file: ""
```

```
$ nim c -r tests/all_tests.nim
Hint: used config file '/opt/homebrew/Cellar/nim/2.2.0/nim/config/nim.cfg' [Conf]
Hint: used config file '/opt/homebrew/Cellar/nim/2.2.0/nim/config/config.nims' [Conf]
Hint: used config file '/Users/x/nimbus-eth2/nim.cfg' [Conf]
Hint: used config file '/Users/x/nimbus-eth2/config.nims' [Conf]
Hint: used config file '/Users/x/nimbus-eth2/tests/nim.cfg' [Conf]
/Users/x/nimbus-eth2/tests/all_tests.nim(1, 2) Error: cannot open file: ""
```
```
$ nimble install
Downloading ssh://git@gitlab.com/metacraft-labs/nimbus/nimbus-security-resources.git using git
       Tip: 3 messages have been suppressed, use --verbose to show them.
tools.nim(62)            tryDoCmdEx

    Error:  Execution of 'git -C /var/folders/q0/t48rpghj67g55mdw8yx1541c0000gn/T/nimble_19851/gitlabcom_metacraftlabsnimbusnimbussecurityresourcesgit_0.1.0_577fbc483f9ffeb715731c9f105f5ac81b3f703a fetch --depth 1 origin 577fbc483f9ffeb715731c9f105f5ac81b3f703a' failed with an exit code 128.
        ... Details: git@gitlab.com: Permission denied (publickey).
        ... fatal: Could not read from remote repository.
        ... Please make sure you have the correct access rights
        ... and the repository exists.
```

**Screenshots**

**Additional context**
I don't understand why there is this dependency which requires ssh instead of https://github.com/status-im/nimbus-security-resources
https://github.com/status-im/nimbus-eth2/blob/f54a0366abfba26c7694fad1e14350d19aa0a228/nimble.lock#L462

**Comment by tersec** [comment]
Did you use the [documented steps](https://nimbus.guide/build.html) for this?

The `nimbus-eth2` repository does not use `nimble`, so running `nimble install` in it doesn't lead to any supported outcomes, including regarding the `nimbus-security-resources` dependency. Rather, it uses [GIt submodules](https://github.com/status-im/nimbus-eth2/tree/stable/vendor).

Regarding `Error: cannot open file: ""`, try running `make update` first.

Also, one of the dependencies bundled is Nim itself. `nimbus-eth2` does not use system Nim and using system Nim does not lead to supported outcomes, either.

To use the bundled version of Nim, one can run, e.g.,
```
$ ./env.sh nim c -r tests/all_tests.nim
```
or
```
$ ./env.sh nim c -r ./scripts/run_ssz_fuzzing_test.nims
```
Incidentally, the latter appears to fail because:
```
nimbus-eth2/scripts/run_ssz_fuzzing_test.nims(9, 24) Error: cannot open file: std/confutils
```
it tries to import a nonexistent standard library. It then fails with various other error messages, which can be looked into, but aren't related to your initial question and aren't in the scope of this issue. That particular script appears not to be particularly maintained or tested regularly.

**Comment by tersec** [comment]
The parts which can be addressed have been addressed; the rest amounts to, `nimbus-eth2` does not currently use Nimble for dependency management, and there's no evidence that documented steps for how to build `nimbus-eth2` were taken.
